name: assets_annotation_by_zpdl
description: annotaion for the assets_generator_by_zpdl package. Incluud only AssetsAnnotation class.
version: 1.4.0
homepage: https://github.com/zpdL-Studio/flutter_assets_generator/tree/main/assets_annotation_by_zpdl

environment:
  sdk: ^3.7.2